approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

# Verhindert die Installation von Paketen, die vor weniger als 24 Stunden veröffentlicht wurden
npmMinimalAgeGate: "24h"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
